/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment3;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A C E R
 */
public class Features extends javax.swing.JFrame {

    ArrayList<Mobile> list;
    String header[] = new String[]{"Name", "No I/C", "Phone No", "Gender", "Address", "Type"};
    DefaultTableModel table;
    /**
     * Creates new form Features
     */
    public Features() {
        initComponents();
        this.setLocationRelativeTo(null);
        list = new ArrayList<Mobile>();
        table = new DefaultTableModel(header, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBCelcom = new javax.swing.JButton();
        jBMaxis = new javax.swing.JButton();
        jBDigi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonShowHistory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMobile = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 255));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INFO AND HISTORY");

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText(" -");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(175, 175, 175)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jLabelMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelClose))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 70);

        jPanel2.setBackground(new java.awt.Color(192, 192, 192));

        jBCelcom.setBackground(new java.awt.Color(128, 128, 0));
        jBCelcom.setText("CELCOM");
        jBCelcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCelcomActionPerformed(evt);
            }
        });

        jBMaxis.setBackground(new java.awt.Color(128, 128, 0));
        jBMaxis.setText("MAXIS");
        jBMaxis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMaxisActionPerformed(evt);
            }
        });

        jBDigi.setBackground(new java.awt.Color(128, 128, 0));
        jBDigi.setText("DIGI");
        jBDigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDigiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("You can click this button to see more info:");

        jLabelBack.setText("   BACK");
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
        });

        jLabel3.setText("All saved records wil be displayed.");

        jButtonShowHistory.setText("SHOW HISTORY");
        jButtonShowHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowHistoryActionPerformed(evt);
            }
        });

        jTableMobile.setBackground(new java.awt.Color(0, 128, 128));
        jTableMobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableMobile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "No I/C", "PhoneNum", "Gender", "Address", "TypeMobile"
            }
        ));
        jTableMobile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMobileMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMobile);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jBCelcom, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBDigi, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBMaxis, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jButtonShowHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCelcom)
                    .addComponent(jBDigi)
                    .addComponent(jBMaxis))
                .addGap(66, 66, 66)
                .addComponent(jButtonShowHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabelBack)
                .addGap(124, 124, 124))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 730, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jBCelcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCelcomActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Type of mobile:CELCOM" + "\nRM3: "+" 1GB(daily)" + "\nRM10: "+" 5GB(weekly)" + "\n10GB free basic internet every month" + "\n1GB free data internet at 8am until 6pm! #StayAtHome" + "\n1.Speed:14.7Mpbs"+ "\n2.HotspotAddOn:RM1 with 1GB in one days & RM3 with 5GB in three days" + "\n3.MonthlyInternet:RM30 with 10GB High-Speed internet & free call to all network");

    }//GEN-LAST:event_jBCelcomActionPerformed

    private void jBMaxisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMaxisActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Type of mobile : MAXIS" + "\nRM3:"+"1GB(daily)" + "\nRM10:"+"5GB(weekly)" + "\n10GB free basic internet every month" + "\n1GB free data internet at 8am until 6pm! #StayAtHome" + "\nSpeed:17.9Mpbs" + "\nPriceHotDeals:" + "\n1.RM3:10GB with 1am until 7am" + "\n2.RM5:Youtube pass unlimited for 1 day" + "\n3.RM6:Music unlimited pass for 1 day");
    }//GEN-LAST:event_jBMaxisActionPerformed

    private void jBDigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDigiActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Type of mobile : DIGI" + "\nRM3:"+"1GB(daily)" + "\nRM10:"+"5GB(weekly)" + "\n10GB free basic internet every month" + "\n1GB free data internet at 8am until 6pm! #StayAtHome" + "\n1.Speed:10.7Mpbs" + "\n2.Midnight:RM2 with 10GB High-Speed internet for only six hour" + "\n3.MonthlyInternet:RM30 with 10GB High-Speed internet & free call to Digi network");
    }//GEN-LAST:event_jBDigiActionPerformed

    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked
        // TODO add your handling code here:
        Menu mn = new Menu();
        mn.setVisible(true);
        mn.pack();
        mn.setLocationRelativeTo(null);
        mn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelBackMouseClicked

    private void jButtonShowHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowHistoryActionPerformed
        // TODO add your handling code here:
        String filePath = "List.txt";
        File file = new File(filePath);
        String readLine = null;

        try {
            FileReader fr=new FileReader(file);
            BufferedReader br=new BufferedReader(fr);
            DefaultTableModel model=(DefaultTableModel)jTableMobile.getModel();

            Object [] lines=br.lines().toArray();
            for(int i=0; i<lines.length; i++){
                String line=lines[i].toString().trim();
                String [] row=line.split(",");
                model.addRow(row);
            }

        } catch (Exception ex) {
            Logger.getLogger(Features.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonShowHistoryActionPerformed

    private void jTableMobileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMobileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableMobileMouseClicked
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Features.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Features.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Features.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Features.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Features().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCelcom;
    private javax.swing.JButton jBDigi;
    private javax.swing.JButton jBMaxis;
    private javax.swing.JButton jButtonShowHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMobile;
    // End of variables declaration//GEN-END:variables
}
